### ISSUE TITLE
Request - Soundtracks update

### ISSUE THREAD

**Issue by GeorgeFive** [duck7000/imdbphp6#29] opened 2023-10-22 12:35 UTC
Would it be possible to expand the soundtracks function to include IMDb ids, and also clean up the output a bit?

Right now, it returns:

```
[0] => Performed by Alice in Chains
[1] => Composed by Alice in Chains
[2] => Produced by Alice in Chains
```

I'd like to see something like this:

```
[performed_by] = Alice in Chains
[performed_by_id] = 2750498
[composed_by] = Alice in Chains
[composed_by_id] = 2750498
[produced_by] = Alice in Chains
[produced_by_id] = 2750498
```

I could easily strip out the "Performed by" part with php, sure, but I just think it would be cleaner to let the user decide how to format it.  I plan on doing a "Band Name - Song Name" list, and having the repeated "Performed by" would look silly in my use case.

Do note that ID is used in the vast majority of cases, but it can be null... example - https://www.imdb.com/title/tt0089907/soundtrack/

Finally... does IMDb return notes as a separate item?  Could we have something like....

```
[performed_by]
    [0] => T.S.O.L.
[performed_by_id]
    [0] => 1830296
[notes]
    [0] => "Used in Hemdale's 1991 Release in lieu of Dead Beat Dance"
```

I see that notes are currently returned, but it is currently impossible to tell if an entry is a note or a credit....
[3] => Produced by Simon Heyworth
[3] => (Used in Hemdale's 1991 Release in lieu of Dead Beat Dance)

I know it's a lot, so let me know what you think!

**Comment by duck7000** [comment] 2023-10-22 14:53
Mm that could be complicated.

Possibly this will cause the same problems as with imdbphp soundtrack, that was a terrible mess to disassemble all different parts, that's why i asked tboothman to finally simplified that method
Imdb GraphQL gives soundtrack, credits and comment, it can be plain text or HTML 
So there are no separate parts, so if you want to disassemble in parts i have to analyze that string, cut it in parts and store it in different array items. The big problem is that those parts can have like 10 different names like explained here
https://help.imdb.com/article/contribution/titles/soundtracks/GKD97LHE9TQ49CZ7#

I will look in to this, but it is complicated. It should be a whole lot easier as IMDb separated that data in GraphQL but sadly they don't

**Comment by duck7000** [comment] 2023-10-22 15:32
Soundtrack title id is possible, all other id's is difficult as they appear only in html. If you want those i have to search in that html is there are anchor links in it..

The soundtrack title is separate and only in text

There are no credits, only array comments which includes credits and comments, so no i can't tell what is credit and what is comment. Every array element that i get from imdb appears to be one credit/comment line, so they are separated by line as displayed on imdb soundtrack pages

So i can change the GraphQL query to get comments in html but if i have to disassemble this in id's, name's etc it will be very hard

![Screenshot_2023-10-22_17-17-22](https://github.com/duck7000/imdbphp6/assets/15360048/2c1c4d8f-7ca6-4a9c-9700-31bf32a7d6e8)

This is screenshot from imdb GraphQL api comments contains everything like comments but also credits. The screenshot is from html version of comments witch contains anchor links from the artist (or performer, writer etc.)
The plainText version does not contain those anchor links (like it is now)

So you see that my options are limited, the only option is to disassemble the html version but it can contain like more than 10 different names like performed by, written by, under courtesy, written and performed etc.

Look at the old version of soundtrack in imdbphp you will see what i mean
https://github.com/tboothman/imdbphp/commit/9dd247233dbdc605b9804ca991e45dc8bc7bb86e

**Comment by GeorgeFive** [comment] 2023-10-22 15:56
Hmm.... so I think this may be a little too much work for too little of a feature.  I think it would be neat to have, but if it's too much (and it looks to be so), this may be something to put on the shelf until they (hopefully) update the way they return their data for us.

**Comment by duck7000** [comment] 2023-10-22 16:55
Yes for now this is not simple to do. It is not the amount work as i'm prepared to do the work, but it is not easy to change it to something you are after

I can add soundtrack title id if that helps (i guess not as that is not where you are after i think)

**Comment by duck7000** [comment] 2023-10-22 17:06
if i had a list of all possible types (performed, written, courtesy, written and performed) etc that would help but there is no list to be found, so far i guess there are 10 - 14 different types but i don't know if there are any more. i do know that there are more types then in the old imdbphp soundtrack method is used.

Still it won't be easy but more possible..

**Comment by GeorgeFive** [comment] 2023-10-23 05:29
With it being more complex than I anticipated, I think I'll leave this one up to you. If you want to put it the work and get it working smoothly, of course I wouldn't complain! But I do understand that this is a bit of a niche request that may not help most people, so I would also understand if you wanted to pass on it. I could more than likely handle the data as is on my end and do something with it, it was just the performer IDs that I was most concerned with.

**Comment by GeorgeFive** [comment] 2023-10-23 09:24
Totally understood, no problems.  I think I could handle it myself on my end, as I only need the "performed by" part and I can just regex that. ID is an issue, but I can likely set up something to connect them manually as needed.

**Comment by duck7000** [comment] 2023-10-23 09:26
If you have/find a way to do it the right way let met know as i need help

**Comment by GeorgeFive** [comment] 2023-10-23 09:53
This was mainly just me thinking out loud, and how I could hack in a bit of a solution on my end (that wouldn't work with this class). I only need performer, so I could regex on the current data that is returned and pull that out (and discard everything else that may be returned, I don't need writers or anything else).

I do store all credits and IDs in my database, so it shouldn't be an issue to select imdb_id where name="Alice In Chains", then probably do some manual clicking if multiple people/ bands with the same name exist.

So I store that connection, and any future soundtrack items for Alice In Chains is already handled.

The only flaw I'm seeing, is if there are multiple bands with the same name... but I guess I could cross that bridge when/ if it happens.

So.... yeah, this is kind of hacky, and wouldn't appeal to everyone, especially if they want all the data. I mainly want to put up a page with what you would see on the back of the CD soundtrack....

1. Alice In Chains - "Grind"
2. Nirvana - "Lithium"
Etc., with band names linked to their respective IDs.

**Comment by duck7000** [comment] 2023-10-23 10:47
Ah i see what you mean now, this is pure your own solution not a "for all" solution

I'll think about it again

**Comment by duck7000** [comment] 2023-10-23 19:57
I labeled this won't fix but feel free to comment again if you have additional info/way to fix this please do

**Comment by duck7000** [comment] 2023-12-10 18:49
@GeorgeFive 
is this still something you are interested in?

I figured that i could add a extra credits_raw array (just like imdphp did) with the html version of soundtrack comments/credits?
This way the data you want is available and the general public does not need to use it if they don't want (like me)

You will have to parse out the data you want yourself as it is too complicated to do it in imdbhp6

**Comment by GeorgeFive** [comment] 2023-12-11 18:05
I never used this in imdbphp to be honest, so I'm not sure how they returned the data. Would it be pretty similar to how I mentioned, or a big block of credits in one string, or....? Definitely curious!

**Comment by duck7000** [comment] 2023-12-11 18:29
The data would be like it is now with credits with the exception that it is html (which include anchor tags in most cases)
You can see what it is like in above screenshot
Every line will have a array item with what is shown in html

No it will not be what you really want but at least you will have the data, you will have to make a foreach to loop that data, determine if it is what you want and puzzle out how to get performer using `stri_pos()`

So no it is not a perfect solution, that would be to hard, to difficult and too complicated.

**Comment by GeorgeFive** [comment] 2023-12-11 19:07
Hmmm.... I'd say just hold back on that. I really don't think it's worth it, I could use the normal version if need be. Thanks anyway though!

**Comment by duck7000** [comment] 2023-12-11 19:16
No problem i just thought of it.

**Comment by duck7000** [comment] 2024-02-26 20:41
@GeorgeFive 

I'm still thinking how we can achieve this mess (and yes it is a mess)

So far i have made a list of different types and names used in Soundtracks, not even sure it is complete but it might a starting point

```
by types:
Arranged by
Composed by
Performed by
Written by
written and Produced by
Written and Performed by
Composed and Performed by
Arranged and Performed by
Performed and hummed by
Music and lyrics by
Adapted and Arranged by
Produced by
Administered by
Conducted by
by
Recorded by
Also performed by
Music by
Lyrics by
Sung by
Sung a cappella by
Introduction by
Words by
Performed on guitar by
Guitar Solo by
Played on piano by
Hummed by
Whistled by
Libretto by
Words and music by
Written & Produced by
Orchestral Arrangement by
Vocals Produced by
Soloist

Not necessarily persons, most likely company:
Licensed by
All rights administered by
Co-Produced by
Additional production by
Published by
By Arrangement with
Courtesy
Courtesy of
Under license from
Based on
Contains a sample of
Used by permission of
Issued under licence from
A Division of
Licensed courtesy of
Licensed with kind permission of
Licensed with courtesy of
With kind authorization of
Master courtesy of
```

You are after performer (a person) so i figured that the last part of this list (company ) is not worth the trouble and would be returned as is with tags stripped?

The  first part of the list is of interest, so far i concluded that if the word "by" is used this mentions a person and so possibly an imdbid

I'm working on a array with all those different names so i can check if it exists in array or not and return a decent name like Performed by would become Performer

So if i split the string after the word "by", check the first part with the array and use the second part to check for names and id's it might be possible to get something working.

I'm carefully optimistic but there is still a lot of uncertainty with this. Maybe i add a parameter that sets if you want creditsplit or not, something like that (this is just a thought for now)

**Comment by duck7000** [comment] 2024-02-27 11:11
@GeorgeFive 
Can you check if there are any more soundtrack credit types like the ones in the above list? They must contain the word by otherwise it would be rather impossible

**Comment by GeorgeFive** [comment] 2024-02-27 19:51
Sounding pretty good so far!  I can't think of any other types off the top of my head, and I've not seen any other new ones in the examples I checked.  Maybe this would be a good time to create an error log function?  If something isn't processed properly, log it and figure out what the problem is.  That would find any stragglers pretty easily, and would be much easier than manually checking for errors.

Will probably also have to work around "as" credits here... ie https://www.imdb.com/title/tt4463894/soundtrack/

Also, haven't forgot about title search advanced, just been incredibly busy with building my new server (done!), updating a lot of code that didn't work properly or threw warnings in newer versions of php (done....?), and real-life work schedule (never done).  Going to try to get to it tonight when I get home.

**Comment by duck7000** [comment] 2024-02-28 10:22
Well a error log function could be helping for future issues but right now this soundtrack issue is already a huge project to deal with. Maybe later..
Actually i am working on this for days now (not all day of course), slowly progress that is..

The "as" issue i thought about and decided to ignore it. You can through the imdbid from this person get that name with the Name class (probably his/her birth name i guess?) If i must consider this too it will be even more complicated as it already is. It may be added later but for now i ignore it, sorry. And you said that the performer id is all you want?

I have some code working but it needs a lot of testing before i consider it working so you can test it. It will take a while.

**Comment by GeorgeFive** [comment] 2024-02-28 18:47
Yeah, the "as" thing isn't something I'm interested in, I just meant that it's a parsing issue to keep in mind.  Wasn't sure if you had seen examples of that.

And yes, the imdb id is all I really need, I plan on using the name class to get all the information I need from that.  If you can keep the by type ("Performed by") in the array, that would be cool, but not required.

Thanks for the work!

**Comment by duck7000** [comment] 2024-02-28 19:25
Yes i have seen those examples, if there is a link i just extracts those links, ignoring the rest.
Performed by will be in the output array as Performer, same for all other "types". If the type is not in my check array it will be returned as text stripped from the word by. If later there are more types i can easily add them.

So far the performer, performer name and performer id, (if available) will be in the output array
if there are no links, then the type (performer etc) and the rest of the text will be in the output array.

At the moment i'm working/dealing with what we consider comments and how they will fit in the output array.

This "project" needs proper testing and probably will not get all cases, so i hope that with your testing the biggest bugs going to be crushed. I other words it will not be perfect, but it will at least find all available links, names, id's and types

Personally i won't be using this but in imdbphp it really frustrated me that it was so complicated and the method they used was a real mess so i want to do better then what they did hah

**Comment by duck7000** [comment] 2024-02-28 21:03
> Performed by will be in the output array as Performer, same for all other "types". If the type is not in my check array it will be returned as text stripped from the word by. If later there are more types i can easily add them.

What do you even want as type? I assumed that 'Performed by' would be converted to Performer but i never asked if you want that?
I can leave it 'Performed by' that will save the trouble with that list as it is returned as i found in the soundtrack text. Below function is in that case not needed

```
    protected function checkSoundtrackType($inputData)
    {
        $str = strtolower($inputData);
        $types = array(
            'composed by' => 'Composer',
            'performed by' => 'Performer',
            'written by' => 'Writer',
            'written and produced by' => 'Writer and Producer',
            'written and performed by' => 'Writer and Performer',
            'composed and performed by' => 'Composer and Performer',
            'arranged and performed by' => 'Arranger and Performer',
            'performed and hummed by' => 'Performer and hummed',
            'music and lyrics by' => 'Music and Lyrics',
            'adapted and arranged by' => 'Adapter and Arranger',
            'produced by' => 'Producer',
            'administered by' => 'administer',
            'conducted by' => 'Conducting',
            'by' => 'By',
            'recorded by' => 'Recording',
            'also performed by' => 'Performer',
            'music by' => 'Music',
            'lyrics by' => 'Lyrics',
            'sung by' => 'Singer',
            'sung a cappella by' => 'Singer A Cappella',
            'introduction by' => 'Introducer',
            'words by' => 'Wording',
            'performed on guitar by' => 'Performer Guitar',
            'guitar Solo by' => 'Guitar Solo',
            'played on piano by' => 'Piano',
            'hummed by' => 'Humming',
            'whistled by' => 'Whistler',
            'libretto by' => 'Libretto',
            'words and music by' => 'Words and Music',
            'written & produced by' => 'Writter and Producer',
            'orchestral arrangement by' => 'Orchestral Arranger',
            'vocals produced by' => 'Vocalist'
        );
        if ($types["$str"] !== false) {
            return $types["$str"];
        } else {
            return trim(str_replace("by", "", $inputData));
        }
    }
```

**Comment by duck7000** [comment] 2024-02-29 11:33
I forgot to add some more types..

```
        $types = array(
            'composed by' => 'Composer',
            'performed by' => 'Performer',
            'written by' => 'Writer',
            'written and produced by' => 'Writer and Producer',
            'written and performed by' => 'Writer and Performer',
            'composed and performed by' => 'Composer and Performer',
            'arranged and performed by' => 'Arranger and Performer',
            'performed and hummed by' => 'Performer and hummed',
            'music and lyrics by' => 'Music and Lyrics',
            'adapted and arranged by' => 'Adapter and Arranger',
            'produced by' => 'Producer',
            'administered by' => 'administer',
            'conducted by' => 'Conducting',
            'by' => 'By',
            'recorded by' => 'Recording',
            'also performed by' => 'Performer',
            'music by' => 'Music',
            'lyrics by' => 'Lyrics',
            'sung by' => 'Singer',
            'sung a cappella by' => 'Singer A Cappella',
            'introduction by' => 'Introducer',
            'words by' => 'Wording',
            'performed on guitar by' => 'Performer Guitar',
            'guitar Solo by' => 'Guitar Solo',
            'played on piano by' => 'Piano',
            'hummed by' => 'Humming',
            'whistled by' => 'Whistler',
            'libretto by' => 'Libretto',
            'words and music by' => 'Words and Music',
            'written & produced by' => 'Writer and Producer',
            'orchestral arrangement by' => 'Orchestral Arranger',
            'vocals produced by' => 'Vocalist',
            'licensed by' => 'Licensed',
            'all rights administered by' => 'All Rights Administered',
            'co-produced by' => 'Co-Producer',
            'additional production by' => 'Additional Production',
            'published by' => 'Publisher'
        );
```

**Comment by duck7000** [comment] 2024-02-29 14:30
[Title.php.tar.gz](https://github.com/duck7000/imdbphp6/files/14449204/Title.php.tar.gz)

I have uploaded title.php for you to test. (when you have time of course)
It might be a older version so only test soundtrack.
There are 2 versions of credits: credits as they are now and creditSplit with the split up variant so both data is available.
I think most cases are covered with names and nameId, the rest is returned either as text or as comment.

doc blocs are not done jet so you have to concentrate on the output array

If there are any problems or you think that something can be improved feel free to let me know.
As i said before it won't be perfect, and my goal was to get the type, name and id from the performer (or other types)

**Comment by duck7000** [comment] 2024-02-29 15:34
Another concern is this:

Performed by [Morgana King](https://www.imdb.com/name/nm0455088/?ref_=ttsnd) (uncredited)

is uncredited in this case important?

**Comment by GeorgeFive** [comment] 2024-02-29 20:14
> protected function checkSoundtrackType
Looks solid to me!  administer should probably be capitalized, that's the only thing I see that should be changed.  As for Published 1951.... that's pretty random.  Is there a possibility of other years for that type?

I pretty much agree with your examples and how to handle them.... let's see....

> Dubbed by is not handled, ignored but link is added (this is not a big problem i guess)
How will that work out?  Do you mean the entire dubbed section is stripped out?  That would be fine, just wanted to make sure I understood that one.

> Not handled, retuned as comment
When we move stuff to a comment like this, will the html be stripped?  I would definitely prefer that, would make things a lot smoother.

I needed to walk out the door ten minutes ago, so I will pick this back up tonight!

**Comment by duck7000** [comment] 2024-02-29 21:08
> > protected function checkSoundtrackType
> > Looks solid to me!  administer should probably be capitalized, that's the only thing I see that should be changed.  As for Published 1951.... that's pretty random.  Is there a possibility of other years for that type?
It passed by so i added it, probably filled in wrong, no idea if this happens often.. 
> 
> I pretty much agree with your examples and how to handle them.... let's see....
> 
> > Dubbed by is not handled, ignored but link is added (this is not a big problem i guess)
> > How will that work out?  Do you mean the entire dubbed section is stripped out?  That would be fine, just wanted to make sure I understood that one.
> 
The text dubbed by is stripped out, the name and id are added
> > Not handled, retuned as comment
> > When we move stuff to a comment like this, will the html be stripped?  I would definitely prefer that, would make things a lot smoother.
> 
Html will always be stripped, including comments. the html is only used to get the name and id
> I needed to walk out the door ten minutes ago, so I will pick this back up tonight!

**Comment by GeorgeFive** [comment] 2024-03-01 07:36
These are the only issues I've found so far.  I obviously haven't tested hundreds of titles yet, but it seems to be a bunch of minor stuff.  Looking good!

> 2e question: do you want nameId to include nm or only digits? through this library only digits are used, i have mixed feelings about that. From a int point of view only digits make sense but from a complete id point of view nm should be included.

Personally, I would prefer to strip out the nm.  I would strip it out on my end otherwise, as I store everything with int (as mentioned) in my database and only append nm or tt when needed.

**Comment by duck7000** [comment] 2024-03-01 15:03
[TitleFixed.tar.gz](https://github.com/duck7000/imdbphp6/files/14462604/TitleFixed.tar.gz)

I made a new version, the approach is different in this one. It will fetch all names and id's if available so it should work better than the first version.
If you have the time check it out please

**Comment by duck7000** [comment] 2024-03-01 20:32
Sung by [Peggy Wood](https://www.imdb.com/name/nm0939931/?ref_=ttsnd) (dubbed by [Margery MacKay](https://www.imdb.com/name/nm0571018/?ref_=ttsnd)), [Anna Lee](https://www.imdb.com/name/nm0496819/?ref_=ttsnd), [Portia Nelson](https://www.imdb.com/name/nm0625675/?ref_=ttsnd), [Marni Nixon](https://www.imdb.com/name/nm0633262/?ref_=ttsnd), [Ada Beth Lee](https://www.imdb.com/name/nm3529693/?ref_=ttsnd), and [Doreen Tryden](https://www.imdb.com/name/nm0874488/?ref_=ttsnd)
Dubbed by is completely ignored in the latest version (no type, name or id are added) so i think that is fine as the dubbed person is not the singer

**Comment by duck7000** [comment] 2024-03-01 20:47
i hope final version..
[Title4.tar.gz](https://github.com/duck7000/imdbphp6/files/14465850/Title4.tar.gz)

Most issues should be crushed (lets hope that imdb accepts my changes)
The issue with the jesus & mary chain remains

**Comment by GeorgeFive** [comment] 2024-03-02 07:06
> The issue with the jesus & mary chain remains
Maybe we could do an easy way with this, and replace "&" with "and" before processing?  This may be a more common problem, there's lots of bands out there with "&" in their name.  I don't think anyone will really care about that replacement, and if they do, they can always run it through the name class to get the & back.

No work tomorrow, so I plan on doing some serious work with this.  Thanks!

**Comment by duck7000** [comment] 2024-03-02 14:54
well the main problem is that i use that & or and as split point to separate the artists
So  i must check if & is used as separator (so i can use it as split point) or that & is in the anchor name

In other words & is used in anchor name AND as separator between artists, the problem is how i deal with that

It is not that simple.

The first title that i uploaded here has a different approach, that fetches only anchor links, but has a problem with mixed artists with a anchor or without, so that doesn't work.
The later versions use explode to break up artist separated by comma. The problem is that there sometimes is a comma, sometimes &, sometimes and. so i replace all those different separators with comma. This works fine but does break up anchors that have & in their name.
This is a nasty problem, and again this comes down to how imdb handles the user input.

**Comment by GeorgeFive** [comment] 2024-03-03 07:28
https://www.imdb.com/title/tt0069091/soundtrack/
Not in array: Written and Sung by

https://www.imdb.com/title/tt0109506/soundtrack/
Not in array: Â©Fractured Music (all rights administered by
Not in array: Written and Arranged by

https://www.imdb.com/title/tt0117330/soundtrack/
Not in array: Written, Performed and Produced by

https://www.imdb.com/title/tt2267968/soundtrack/
Not in array: Production supervised by

"Lyricsist" is misspelled = Lyricist

https://www.imdb.com/title/tt1302011/soundtrack/
Not in array: Used by

https://www.imdb.com/title/tt0072431/soundtrack/
Not in array: Sung and Danced by
Not in array: Also sung by

https://www.imdb.com/title/tt1431045/soundtrack/
Not in array: Courtesy of Barnaby
Not in array: (contains a sample of "Low Rider" performed by

https://www.imdb.com/title/tt5334704/soundtrack/
Not in array: Guitar by

https://www.imdb.com/title/tt1051906/soundtrack/
Not in array: (c) Published by
Not in array: (c) Published by
Not in array: (c) Quiet as Kept Music Inc. Licensed by
^^Which is weird because I don't even see this data displayed on their page.

https://www.imdb.com/title/tt0167260/soundtrack/
Not in array: Adapted by
Not in array: Orchestration by

https://www.imdb.com/title/tt0109830/soundtrack/
Not in array: Adaption and Music by

https://www.imdb.com/title/tt0088763/soundtrack/
The Jesus & Mary Chain example worked great, but it's not working as well with Huey Lewis & The News... it returns double results, one right, one not.
>                     [0] => Array
                        (
                            [creditType] => Performer
                            [name] => Huey Lewis & The News
                            [nameId] => 3539158
                        )

                    [1] => Array
                        (
                            [creditType] => Performer
                            [name] => The News)
                            [nameId] => 
                        )

**Comment by GeorgeFive** [comment] 2024-03-03 07:37
So it seems like the only real issues now is the "not in array" stuff, which will undoubtedly be endless.

When I actually start running this and not just testing it, it'll be in automatic mode and I won't be catching this stuff... maybe a simple error log function?  Could be something as simple as this - https://www.geeksforgeeks.org/how-to-log-errors-and-warnings-into-a-file-in-php/

**Comment by duck7000** [comment] 2024-03-03 11:23
> https://www.imdb.com/title/tt0069091/soundtrack/ Not in array: Written and Sung by
> 
> https://www.imdb.com/title/tt0109506/soundtrack/ Not in array: Â©Fractured Music (all rights administered by Not in array: Written and Arranged by
> 
> https://www.imdb.com/title/tt0117330/soundtrack/ Not in array: Written, Performed and Produced by
> 
> https://www.imdb.com/title/tt2267968/soundtrack/ Not in array: Production supervised by
> 
> "Lyricsist" is misspelled = Lyricist
> 
> https://www.imdb.com/title/tt1302011/soundtrack/ Not in array: Used by
> 
> https://www.imdb.com/title/tt0072431/soundtrack/ Not in array: Sung and Danced by Not in array: Also sung by
> 
> https://www.imdb.com/title/tt1431045/soundtrack/ Not in array: Courtesy of Barnaby Not in array: (contains a sample of "Low Rider" performed by
> 
> https://www.imdb.com/title/tt5334704/soundtrack/ Not in array: Guitar by
> 
> https://www.imdb.com/title/tt1051906/soundtrack/ Not in array: (c) Published by Not in array: (c) Published by Not in array: (c) Quiet as Kept Music Inc. Licensed by ^^Which is weird because I don't even see this data displayed on their page.
> 
> https://www.imdb.com/title/tt0167260/soundtrack/ Not in array: Adapted by Not in array: Orchestration by
> 
> https://www.imdb.com/title/tt0109830/soundtrack/ Not in array: Adaption and Music by
> 
> https://www.imdb.com/title/tt0088763/soundtrack/ The Jesus & Mary Chain example worked great, but it's not working as well with Huey Lewis & The News... it returns double results, one right, one not. `` ( [creditType] => Performer [name] => Huey Lewis & The News [nameId] => 3539158 ) [1] => Array ( [creditType] => Performer [name] => The News) [nameId] => )

Well all not in array is a nightmare and we should abandon this. This will never work right. I suggest to remove this and return everything as is stripped from the word by? Or completely as is?

The jesus & mary chain works indeed but not if that is no anchor link. Like i said it is impossible to no if the '&' is used inside a name or as separator between artists (both are used)

And to make matters worse imdb allows '/' as separator between artists as well so i have to factor that in as well..

I told you up front that this is no easy task and i begin to think it might not be possible to catch all cases

**Comment by duck7000** [comment] 2024-03-03 11:30
> So it seems like the only real issues now is the "not in array" stuff, which will undoubtedly be endless.
> 
> When I actually start running this and not just testing it, it'll be in automatic mode and I won't be catching this stuff... maybe a simple error log function? Could be something as simple as this - https://www.geeksforgeeks.org/how-to-log-errors-and-warnings-into-a-file-in-php/

I will look in to this

The big question is what would be have to logged?

**Comment by GeorgeFive** [comment] 2024-03-03 12:03
I have a feeling that I could test 100 more movies, and find 80 more "by" entries.  Maybe we should step back and simplify this a bit.  Instead of trying to grab every possible "by" out there, we focus more on the standard ones?  Performed, written, produced, composed, etc.  If we want the ids and name data for the "meat" of the credit, we can use creditSplit.... if we want every possible nugget of information, we use credits.

Might also make it a little easier to find the "X and X by" entries... ie, run a regex on "Written and Performed by", find "Written", give a writer credit, find "Performed", give a performed credit.... remove the "Written and Performed by" altogether.

Things like "Sung and Danced by" could be stripped entirely from creditSplit, nothing listed in the credits section even if there is a name id... but we could leave it in the main credits part of the array for completeness.

**Comment by duck7000** [comment] 2024-03-03 12:12
I don't completely understand what you mean but i suggest that i remove the whole function with all the different types.

I return the X by string as is, or stripped from by?
What you want with this info is then up to you?
I hate regex, this will complicate things even more

**Comment by GeorgeFive** [comment] 2024-03-03 12:24
So in the array, we keep the credits section as is.  It has all the data, no ids, just a nice chunk of text with every possible thing in it.  We don't need to scan it or play with it, we just get it straight from imdb and leave it as is now.

creditSplit will get the main data, but not all the niche data.

If it says "Performed by", "Performed and written by", "Performed and produced by", "Performed and dreamed by", "Performed and typoblah by".... anything like that.... we skim for the word "Performed" and give them a performed credit.

Same thing with "Written _______", "Produced _____", "Composed ______", "Conducted".... that may be enough?

So in this case, the creditType field would only have five possible values... if it doesn't match one of the above words, we ignore it in creditSplit (but leave it in the main credits part of the array).

I think this may be the direction to go, because we will never get all possible "by" values, and any regex trickery we come up with to try to solve this will inevitably break something else.  I'd rather focus on the base data, and know that it is right, than worry about the niche case of "hummed by" popping up.

**Comment by duck7000** [comment] 2024-03-03 12:32
Ah okay i see what you mean now

credits is and will always remain like it is now and contains all data in text form

creditSplit get only creditType if it is one of those main types, ignore the rest? (Or a default type?)
So we focus on the first main word of type

I will try, may be tonight

**Comment by GeorgeFive** [comment] 2024-03-03 12:39
Pretty much, yep.  Not necessarily focus on only the first word though, we would pick keywords from the string itself.

Main credits gets everything and stays as is.

creditSplit example
Performed by = performer credit
Performed and written by = performer credit and writer credit
Performed, written, and hummed by = performer credit, writer credit, ignore hummed

**Comment by duck7000** [comment] 2024-03-03 14:58
> Performed and written by = performer credit and writer credit

This would mean that the creditor will be added 2 times (or more) to creditSplit? That means i have to split up the part before by and use it twice as creditType.
This part will get more complicated (the other part was already a nightmare, but finally acceptable)

**Comment by GeorgeFive** [comment] 2024-03-03 15:05
Would it be easier to have them combined?  I thought skimming for keywords would make it a little easier.

**Comment by duck7000** [comment] 2024-03-03 15:18
> Would it be easier to have them combined? I thought skimming for keywords would make it a little easier.

Yes absolute, like a said i return it as is (Performed and Written by) with or without by would be much easier.
In my view that make sence as the data is presented that way?

Again this comes also back to the way imdb let users input the soundtrack data..

**Comment by GeorgeFive** [comment] 2024-03-03 15:35
Ok, that definitely works for me then.  I thought it would be easier to skim for keywords, so we don't have to worry about edge cases.  But I'm good with whatever is easiest!

**Comment by duck7000** [comment] 2024-03-03 16:25
well the easiest would be... not to use this method hahaha

But yes i like the KISS principle (keep it simple stupid) and our method is already very complex.

And if you consider this soundtrack page it is going to get even worse
https://www.imdb.com/title/tt0252444/soundtrack/

Featuring is already a problem
CreditType separated by : is also not covered

And in other soundtracks the creditors are separated by '/' which is also not covered

So you see this will be going on and on..

**Comment by duck7000** [comment] 2024-03-06 20:29
I consider this splitup variant as working, but yes there will be cases not covered, but that will only occur in text form afaik

Do you want a final check?
[Title_final.tar.gz](https://github.com/duck7000/imdbphp6/files/14515218/Title_final.tar.gz)
Only use soundtrack from this title.php

**Comment by GeorgeFive** [comment] 2024-03-06 22:37
Yeah, let me give this another round of testing tonight, my focus pretty much went entirely to titlesearch recently, hah.

**Comment by duck7000** [comment] 2024-03-08 11:26
There might be one problem left

When there is no by but instead a : 
Do you want to replace it with by so the method can deal with this situation as well (it does occur but not that often)
It can however create new problems, what if there is a : in the string but for a different purpose? It can create the same situation as with the word and

**Comment by duck7000** [comment] 2024-03-08 21:18
[Title8.tar.gz](https://github.com/duck7000/imdbphp6/files/14543252/Title8.tar.gz)

**Comment by duck7000** [comment] 2024-03-17 21:50
I just added the soundtrack creditSpit, as far as i tested it works

If @GeorgeFive you find any problems with it report it here and i re open this

**Closed by duck7000** 2024-03-17 21:50 UTC
Labels: enhancement

**Comment by GeorgeFive** [comment] 2024-03-17 21:59
Sounds good!  Haven't had time to play with this, had a bit of a medical emergency last week and haven't been able to focus due to pain pills.  Lovely....

**Comment by duck7000** [comment] 2024-03-18 11:25
Oh that sucks man, i wish you well and soon recovery!

It wasn't meant to rush you or anything, i just added it so it is done. If there are still issues we can deal with it later on.
I added a bunch of other methods as well just for completeness
